name: CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Server Deployment
    runs-on: img-ubuntu-22.04
    defaults:
      run:
        working-directory: infra

    env:
      # Postgres
      COS_POSTGRES_USER: ${{ secrets.COS_POSTGRES_USER }}
      COS_POSTGRES_PASSWORD: ${{ secrets.COS_POSTGRES_PASSWORD }}
      COS_POSTGRES_DB: ${{ secrets.COS_POSTGRES_DB }}
      COS_POSTGRES_PORT: ${{ secrets.COS_POSTGRES_PORT }}
      COS_POSTGRES_CONTAINER: ${{ secrets.COS_POSTGRES_CONTAINER }}

      # RabbitMQ
      COS_RABBITMQ_USER: ${{ secrets.COS_RABBITMQ_USER }}
      COS_RABBITMQ_PASSWORD: ${{ secrets.COS_RABBITMQ_PASSWORD }}
      COS_RABBITMQ_PORT: ${{ secrets.COS_RABBITMQ_PORT }}
      COS_RABBITMQ_MANAGEMENT_PORT: ${{ secrets.COS_RABBITMQ_MANAGEMENT_PORT }}
      COS_RABBITMQ_CONTAINER: ${{ secrets.COS_RABBITMQ_CONTAINER }}
      COS_RABBITMQ_HOST: ${{ secrets.COS_RABBITMQ_HOST }}

      # ClickHouse
      COS_CLICKHOUSE_PORT_HTTP: ${{ secrets.COS_CLICKHOUSE_PORT_HTTP }}
      COS_CLICKHOUSE_PORT_NATIVE: ${{ secrets.COS_CLICKHOUSE_PORT_NATIVE }}
      COS_CLICKHOUSE_CONTAINER: ${{ secrets.COS_CLICKHOUSE_CONTAINER }}

      # Elastic / Kibana / Logstash
      COS_ELASTICSEARCH_PORT: ${{ secrets.COS_ELASTICSEARCH_PORT }}
      COS_ELASTICSEARCH_CONTAINER: ${{ secrets.COS_ELASTICSEARCH_CONTAINER }}
      ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
      COS_KIBANA_PORT: ${{ secrets.COS_KIBANA_PORT }}
      COS_KIBANA_CONTAINER: ${{ secrets.COS_KIBANA_CONTAINER }}
      KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
      COS_LOGSTASH_PORT: ${{ secrets.COS_LOGSTASH_PORT }}
      COS_LOGSTASH_CONTAINER: ${{ secrets.COS_LOGSTASH_CONTAINER }}
      COS_LOGSTASH_HOST: ${{ secrets.COS_LOGSTASH_HOST }}

      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      COS_REST_API_CONTAINER: ${{ secrets.COS_REST_API_CONTAINER }}
      TELEGRAM_ADMIN_ID: ${{ secrets.TELEGRAM_ADMIN_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show Docker versions
        run: |
          docker --version || true
          docker compose version || true

      - name: Pick compose file (infra or infra/production)
        id: pick
        run: |
          set -euo pipefail
          if [ -f "docker-compose.yml" ]; then
            echo "file=docker-compose.yml" >> "$GITHUB_OUTPUT"
          elif [ -f "production/docker-compose.yml" ]; then
            echo "file=production/docker-compose.yml" >> "$GITHUB_OUTPUT"
          else
            echo "Не найден docker-compose.yml ни в infra/, ни в infra/production/"
            ls -la
            exit 1
          fi
          echo "Используем compose файл: $(cat "$GITHUB_OUTPUT" | sed -n 's/^file=//p')"

      - name: Docker Compose down
        run: |
          docker compose -f "${{ steps.pick.outputs.file }}" down || true

      - name: Docker Compose up (build)
        run: |
          docker compose -f "${{ steps.pick.outputs.file }}" pull || true
          docker compose -f "${{ steps.pick.outputs.file }}" up -d --build --remove-orphans

      - name: Debug on failure
        if: failure()
        run: |
          echo "--- docker ps ---"
          docker ps -a || true
          echo "--- compose ls ---"
          docker compose -f "${{ steps.pick.outputs.file }}" ls || true
          echo "--- compose logs (last 200 lines per service) ---"
          services=$(docker compose -f "${{ steps.pick.outputs.file }}" config --services || true)
          for s in $services; do
            echo "### $s"
            docker compose -f "${{ steps.pick.outputs.file }}" logs --no-color --tail=200 "$s" || true
          done
