name: CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Server Deployment
    runs-on: img-ubuntu-22.04
    # Если нет метки образа у раннера, используй:
    # runs-on: self-hosted

    # "Переход" в каталог infra — все run-скрипты выполняются из этой папки
    defaults:
      run:
        working-directory: infra

    env:
      # Postgres
      SN_POSTGRES_USER: ${{ secrets.SN_POSTGRES_USER }}
      SN_POSTGRES_PASSWORD: ${{ secrets.SN_POSTGRES_PASSWORD }}
      SN_POSTGRES_DB: ${{ secrets.SN_POSTGRES_DB }}
      SN_POSTGRES_PORT: ${{ secrets.SN_POSTGRES_PORT }}
      SN_POSTGRES_CONTAINER: ${{ secrets.SN_POSTGRES_CONTAINER }}

      # RabbitMQ
      SN_RABBITMQ_USER: ${{ secrets.SN_RABBITMQ_USER }}
      SN_RABBITMQ_PASSWORD: ${{ secrets.SN_RABBITMQ_PASSWORD }}
      SN_RABBITMQ_PORT: ${{ secrets.SN_RABBITMQ_PORT }}
      SN_RABBITMQ_MANAGEMENT_PORT: ${{ secrets.SN_RABBITMQ_MANAGEMENT_PORT }}
      SN_RABBITMQ_CONTAINER: ${{ secrets.SN_RABBITMQ_CONTAINER }}
      SN_RABBITMQ_HOST: ${{ secrets.SN_RABBITMQ_HOST }}

      # ClickHouse
      SN_CLICKHOUSE_PORT_HTTP: ${{ secrets.SN_CLICKHOUSE_PORT_HTTP }}
      SN_CLICKHOUSE_PORT_NATIVE: ${{ secrets.SN_CLICKHOUSE_PORT_NATIVE }}
      SN_CLICKHOUSE_CONTAINER: ${{ secrets.SN_CLICKHOUSE_CONTAINER }}

      # Elastic / Kibana / Logstash
      SN_ELASTICSEARCH_PORT: ${{ secrets.SN_ELASTICSEARCH_PORT }}
      SN_ELASTICSEARCH_CONTAINER: ${{ secrets.SN_ELASTICSEARCH_CONTAINER }}
      ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
      SN_KIBANA_PORT: ${{ secrets.SN_KIBANA_PORT }}
      SN_KIBANA_CONTAINER: ${{ secrets.SN_KIBANA_CONTAINER }}
      KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
      SN_LOGSTASH_PORT: ${{ secrets.SN_LOGSTASH_PORT }}
      SN_LOGSTASH_CONTAINER: ${{ secrets.SN_LOGSTASH_CONTAINER }}
      SN_LOGSTASH_HOST: ${{ secrets.SN_LOGSTASH_HOST }}

      # App / misc
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      SN_REST_API_CONTAINER: ${{ secrets.SN_REST_API_CONTAINER }}
      TELEGRAM_ADMIN_ID: ${{ secrets.TELEGRAM_ADMIN_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show Docker versions
        run: |
          docker --version || true
          docker compose version || true

      - name: Pick compose file (infra or infra/production)
        id: pick
        run: |
          set -euo pipefail
          if [ -f "docker-compose.yml" ]; then
            echo "file=docker-compose.yml" >> "$GITHUB_OUTPUT"
          elif [ -f "production/docker-compose.yml" ]; then
            echo "file=production/docker-compose.yml" >> "$GITHUB_OUTPUT"
          else
            echo "❌ Не найден docker-compose.yml ни в infra/, ни в infra/production/"
            ls -la
            exit 1
          fi
          echo "✅ Используем compose файл: $(cat "$GITHUB_OUTPUT" | sed -n 's/^file=//p')"

      - name: Docker Compose down
        run: |
          docker compose -f "${{ steps.pick.outputs.file }}" down || true

      - name: Docker Compose up (build)
        run: |
          docker compose -f "${{ steps.pick.outputs.file }}" pull || true
          docker compose -f "${{ steps.pick.outputs.file }}" up -d --build --remove-orphans

      # Диагностика при падении
      - name: Debug on failure
        if: failure()
        run: |
          echo "--- docker ps ---"
          docker ps -a || true
          echo "--- compose ls ---"
          docker compose -f "${{ steps.pick.outputs.file }}" ls || true
          echo "--- compose logs (last 200 lines per service) ---"
          # Печатаем последние строки логов каждого сервиса, если нужно – увеличь tail
          services=$(docker compose -f "${{ steps.pick.outputs.file }}" config --services || true)
          for s in $services; do
            echo "### $s"
            docker compose -f "${{ steps.pick.outputs.file }}" logs --no-color --tail=200 "$s" || true
          done
