"""Removed products

Revision ID: 1ac32da688ab
Revises: 7a19b11e64d2
Create Date: 2025-10-07 15:47:34.786740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ac32da688ab'
down_revision: Union[str, Sequence[str], None] = '7a19b11e64d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_video_association')
    op.drop_table('product')
    op.add_column('channels', sa.Column('start_views', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('start_likes', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('start_comments', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('article', sa.String(), nullable=True))
    op.drop_column('videos', 'published_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('published_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('videos', 'article')
    op.drop_column('channels', 'start_comments')
    op.drop_column('channels', 'start_likes')
    op.drop_column('channels', 'start_views')
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('article_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('s3_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product_video_association',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('product_video_association_product_id_fkey')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('product_video_association_video_id_fkey')),
    sa.PrimaryKeyConstraint('product_id', 'video_id', name=op.f('product_video_association_pkey'))
    )
    # ### end Alembic commands ###
