"""change time

Revision ID: 48bcd0357aa1
Revises: 69fcc76491db
Create Date: 2025-10-09 16:37:38.831320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bcd0357aa1'
down_revision: Union[str, Sequence[str], None] = '69fcc76491db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('video_history', 'date_published',
#                existing_type=sa.INTEGER(),
#                type_=sa.DateTime(),
#                existing_nullable=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('video_history', 'date_published',
#                existing_type=sa.DateTime(),
#                type_=sa.INTEGER(),
#                existing_nullable=True)
#     # ### end Alembic commands ###

def upgrade():
    op.drop_column('video_history', 'date_published')
    op.add_column('video_history', sa.Column('date_published', sa.DateTime(), nullable=True))

def downgrade():
    op.drop_column('video_history', 'date_published')
    op.add_column('video_history', sa.Column('date_published', sa.Integer(), nullable=True))