"""Yes

Revision ID: 69fcc76491db
Revises: 1ac32da688ab
Create Date: 2025-10-09 15:38:32.572417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fcc76491db'
down_revision: Union[str, Sequence[str], None] = '1ac32da688ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_history', sa.Column('date_published', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_history', 'date_published')
    # ### end Alembic commands ###
