"""rename

Revision ID: f82f74cd21d0
Revises: 23786ad71cc4
Create Date: 2025-10-15 12:45:22.959504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82f74cd21d0'
down_revision: Union[str, Sequence[str], None] = '23786ad71cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('articles', sa.String(), nullable=True))
    op.create_index(op.f('ix_videos_articles'), 'videos', ['articles'], unique=False)
    op.drop_column('videos', 'article')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('article', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_videos_articles'), table_name='videos')
    op.drop_column('videos', 'articles')
    # ### end Alembic commands ###
